<?php

/**
 * @file
 * Primary module hooks for Performance Lab module.
 */

use Drupal\user\UserInterface;

/**
 * Implements hook_user_cancel().
 */
function performance_lab_user_cancel($edit, UserInterface $account, $method): void {
  switch ($method) {
    case 'user_cancel_block_unpublish':
      // Unpublish products.
      $storage = \Drupal::entityTypeManager()->getStorage('performance_lab_product');
      $performance_lab_product_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->condition('status', 1)
        ->accessCheck(FALSE)
        ->execute();

      /** @var \Drupal\performance_lab\ProductInterface */
      foreach ($storage->loadMultiple($performance_lab_product_ids) as $performance_lab_product) {
        $performance_lab_product->set('status', FALSE)->save();
      }
      break;

    case 'user_cancel_reassign':
      // Anonymize products.
      $storage = \Drupal::entityTypeManager()->getStorage('performance_lab_product');
      $performance_lab_product_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->accessCheck(FALSE)
        ->execute();

      /** @var \Drupal\performance_lab\ProductInterface */
      foreach ($storage->loadMultiple($performance_lab_product_ids) as $performance_lab_product) {
        $performance_lab_product->setOwnerId(0)->save();
      }
      break;
  }
}

/**
 * Implements hook_ENTITY_TYPE_predelete() for user entities.
 */
function performance_lab_user_predelete(UserInterface $account): void {
  // Delete products that belong to this account.
  $storage = \Drupal::entityTypeManager()->getStorage('performance_lab_product');
  $performance_lab_product_ids = $storage->getQuery()
    ->condition('uid', $account->id())
    ->accessCheck(FALSE)
    ->execute();

  $storage->delete(
    $storage->loadMultiple($performance_lab_product_ids)
  );
}
