name: Deploy to Pantheon

on:
  workflow_run:
    workflows: ["Drupal CI"]
    types:
      - completed

jobs:
  deploy:
    concurrency:
      group: pantheon-deploy-dev
      cancel-in-progress: true

    if: >
      ${{
        github.event.workflow_run.conclusion == 'success' &&
        github.event.workflow_run.head_branch == 'develop'
      }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      # Deploy to Pantheon
      - name: Authenticate and Push to Pantheon
        uses: pantheon-systems/push-to-pantheon@0.9.2
        with:
          ssh_key: ${{ secrets.SSH_PRIVATE_KEY }}
          machine_token: ${{ secrets.PANTHEON_MACHINE_TOKEN }}
          site: ${{ vars.PANTHEON_SITE_NAME }}
          target_env: dev



