name: Deploy to Pantheon

on:
  workflow_run:
    workflows: ["Drupal CI"]
    types:
      - completed
  push:
    branches: [ develop ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      # Deploy to Pantheon
      - name: Authenticate and Push to Pantheon
        uses: pantheon-systems/push-to-pantheon@0.9.2
        with:
          ssh_key: ${{ secrets.SSH_PRIVATE_KEY }}
          machine_token: ${{ secrets.PANTHEON_MACHINE_TOKEN }}
          site: ${{ vars.PANTHEON_SITE_NAME }}
          target_env: dev

      - name: Wait until Drupal is ready
        run: |
          SITE_ENV="${{ vars.PANTHEON_SITE_NAME }}.dev"

          echo "Waiting for Drupal to be ready..."

          for i in {1..30}; do
            if terminus drush $SITE_ENV -- status > /dev/null 2>&1; then
              echo "Drupal is ready!"
              break
            fi

            echo "Attempt $i: Drupal not ready yet..."
            sleep 10
          done

      - name: Force Git Mode
        run: terminus connection:set ${{ vars.PANTHEON_SITE_NAME }}.dev git

      - name: Run Drush commands on Pantheon with terminus
        run: |
          SITE_ENV="${{ vars.PANTHEON_SITE_NAME }}.dev"

          # 4. Running Drush commands.
          echo "Initial cache cleanning..."
          terminus drush $SITE_ENV -- cr

          echo "Running database updates (updb)..."
          terminus drush $SITE_ENV -- updb -y

          echo "Importing database configurations (cim)..."
          terminus drush $SITE_ENV -- cim -y

          echo "Final cache clean up..."
          terminus drush $SITE_ENV -- cr

          echo "🚀 ¡Deployment and update completed successfully!"



