name: Main Workflow

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ main ]

env:
  # shivammathur/setup-php
  PHP_EXTENSIONS: dom, curl, libxml, mbstring, zip, pdo, mysql, pdo_mysql, bcmath, gd, exif, iconv
  PHP_VERSION: 8.4

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup PHP with composer v2
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}
          extensions: ${{ env.PHP_EXTENSIONS }}
          tools: composer:v2
          coverage: none

      # Cache Logic for Composer dependencies.
      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache Composer dependencies
        uses: actions/cache@v5
        with:
          path: ~/.cache/composer
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Validate composer
        run: composer validate

      - name: Install Dependencies
        run: composer install --no-progress --no-interaction --prefer-dist --optimize-autoloader

      # Run PHPCS (Drupal standards) and PHPStan (Drupal rules).
      # These tools will help ensure code quality and adherence to Drupal coding standards.
      # IF these steps fail, the workflow will stop, preventing any further actions (like deployment) from executing.
      - name: Run PHPCS (Drupal standards)
        run: vendor/bin/phpcs --standard=Drupal web/modules/custom

      - name: Run PHPStan (Drupal rules)
        run: vendor/bin/phpstan analyse -c phpstan.neon web/modules/custom

      # Save preview result (Including vendor) as artifact for the next job.
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: drupal-app-builder
          path: .
          retention-days: 1

  # Deploy and pantheon management.
  deploy:
    needs: build
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: Download Build Artifacts
        uses: actions/download-artifact@v8
        with:
          name: drupal-app-builder

      # Deploy to Pantheon
      - name: Authenticate and Push to Pantheon
        uses: pantheon-systems/push-to-pantheon@0.9.2
        with:
          ssh_key: ${{ secrets.SSH_PRIVATE_KEY }}
          machine_token: ${{ secrets.PANTHEON_MACHINE_TOKEN }}
          site: ${{ vars.PANTHEON_SITE_NAME }}
          target_env: dev

      - name: Force Git Mode
        run: terminus connection:set $SITE_ENV git

      - name: Run Drush commands on Pantheon
        run: |
          SITE_ENV="${{ vars.PANTHEON_SITE_NAME }}.dev"

          # Polling process to wait for Pantheon to finish processing the push and be ready for Drush commands.
          # 1. Get the current SHA commit that triggered the workflow.
          CURRENT_COMMIT=$(git rev-parse HEAD)
          echo "Checking for synchonization for confirmation: $CURRENT_COMMIT"

          # 2. Polling loop (Check every 10 seg, up to 12 times = 2 minutes)
          echo "Starting synchonization check with Pantheon..."

          for 1 in {1..12}; do
            # Get the last commit hash known to Pantheon for the target environment.
            DEPLOYED_SHA=$(terminus env:code-log ${{ vars.PANTHEON_SITE_NAME }}.dev --format=json | jq -r '.[0].hash')

            if [ "$DEPLOYED_SHA" == "$CURRENT_COMMIT" ]; then
              echo "✅ ¡Confirmed! The code is already synchronized in Pantheon."
              break
            fi

            if [ $i -eq 12 ]; then
              echo "⚠️ The timeout has expired. Attemting to run Drush anyway..."
            else
              echo "Synchronizing... (Attempt $i/12). Wait 10 more seconds.."
              sleep 10
            fi
          done

          # 3. Setting up the environment.
          echo "Forcing cache cleaning on environments..."
          terminus env:clear-cache $SITE_ENV -y

          # 4. Running Drush commands.
          echo "Initial cache cleanning..."
          terminus drush $SITE_ENV -- cr

          echo "Running database updates (updb)..."
          terminus drush $SITE_ENV -- updb -y || (echo "Initial failure, retrying updn..." && sleep 10 && terminus drush $SITE_ENV -- updb -y)

          echo "Importing database configurations (cim)..."
          terminus drush $SITE_ENV -- cim -y

          echo "Final cache clean up..."
          terminus drush $SITE_ENV -- cr

          echo "🚀 ¡Deployment and update completed successfully!"



